g .sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.1.5

env:
  - DB=postgres

cache: bundler
bundler_args: --path=vendor/bundle --without heroku

before_script:
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database ffcrm_api_test;' -U postgres; fi"

# Run specs
script: "bundle exec rake"
